apiVersion: apps/v1
kind: Deployment
metadata:
  name: pants-fe
  namespace: web
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pants-fe
  template:
    metadata:
      labels:
        app: pants-fe
    spec:
      containers:
        - name: pants-fe
          image: chickennight/pants-fe:0.2.7
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://pants-be-service.web.svc.cluster.local"
            - name: REACT_APP_API_URL
              value: "https://www.wordsketch.site"
