apiVersion: v1
kind: Service
metadata:
  name: pants-fe-service
  namespace: argocd
spec:
  selector:
    app: pants-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
