apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: web
type: Opaque
data:
  GOOGLE_CLIENT_ID: NjExMzMzNjAwNzgtcXNkY2VycDY4MGJrcjJ2ZXZuOHVjZ2Q1YzM5cW1mcGUuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20=
  GOOGLE_CLIENT_SECRET: R09DU1BYLUtWOURpNFVoUUZCNTV6Z1FxV2hBSWdsUzZyUC0=
  GOOGLE_REDIRECT_URI: aHR0cDovL3d3dy53b3Jkc2tldGNoLnNpdGUvbG9naW4vb2F1dGgyL2NvZGUvZ29vZ2xl
  GITHUB_CLIENT_ID: NTkyMzUwMTMyNjJiMjMwM2U0OTU=
  GITHUB_CLIENT_SECRET: ZjQ4ODFhNWU5ZjIyZmVkYWU4MTY4ZjhhZjI5NmZhZGYyYmMxOTlkZA==
  GITHUB_REDIRECT_URI: aHR0cDovL3d3dy53b3Jkc2tldGNoLnNpdGUvbG9naW4vb2F1dGgyL2NvZGUvZ2l0aHVi
  KAKAO_CLIENT_ID: YjliMDIzNDVhYmI0YzQyNTk0YjQxZTU5MGUyOWY3NTk=
  KAKAO_CLIENT_SECRET: T3NLbkJmb3hwbENETDJVR2VraFB1cjdIcXEwdkJ6aXk=
  KAKAO_REDIRECT_URI: aHR0cDovL3d3dy53b3Jkc2tldGNoLnNpdGUvbG9naW4vb2F1dGgyL2NvZGUva2FrYW8=
  JWT_SECRETKEY: Z2FzZGZhc2Zhc2dmc2Rnc2RmaGdzZGdzZGdzZGdzZGdzZGZnc2RmMTMxMjNkd2cxMTJmcWZnMTIzMWZzZ3FlZ2txd1tma2dbMjMxMjNrazJbaw==
