apiVersion: v1
kind: Service
metadata:
  name: pants-be-service
spec:
  selector:
    app: pants-be
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pants-be-deployment
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pants-be
  template:
    metadata:
      labels:
        app: pants-be
    spec:
      containers:
        - name: pants-be
          image: chickennight/pants-be:latest
          ports:
            - containerPort: 8080
        env:
        - name: DATASOURCE_URL
          value: jdbc:postgresql://${DB_ENDPOINT}:${DB_PORT}/wordsketch?serverTimezone=UTC+9&characterEncoding=UTF-8
        - name: DATASOURCE_USERNAME
          value: postgres
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: DB_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: endpoint
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: port
