apiVersion: apps/v1
kind: Deployment
metadata:
  name: pants-be-deployment
  namespace: web
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pants-be
  template:
    metadata:
      labels:
        app: pants-be
    spec:
      containers:
        - name: pants-be
          image: chickennight/pants-be:0.1.5
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
