apiVersion: v1
kind: Service
metadata:
  name: pants-be-service
  namespace: web
spec:
  selector:
    app: pants-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  sessionAffinity: ClientIP // 동일한 팟으로 세션요청 유지
