apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-cronjob
  namespace: web
spec:
  schedule: "0 2 * * *"  # 매일 오전 2시에 실행
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-container
            image: chickennight/batch-server:0.1.0
            env:
              - name: DATASOURCE_URL
                value: jdbc:postgresql://${DB_ENDPOINT}:${DB_PORT}/wordsketch?serverTimezone=UTC+9&characterEncoding=UTF-8
              - name: DATASOURCE_USERNAME
                value: postgres
              - name: DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: password
              - name: DB_ENDPOINT
                valueFrom:
                  configMapKeyRef:
                    name: db-config
                    key: endpoint
              - name: DB_PORT
                valueFrom:
                  configMapKeyRef:
                    name: db-config
                    key: port
              - name: AWS_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-secret
                    key: aws_access_key_id
              - name: AWS_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-secret
                    key: aws_secret_access_key
              - name: OPENAI_KEY
                valueFrom:
                  secretKeyRef:
                    name: openai-secret
                    key: api_key
            restartPolicy: OnFailure
