apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-cronjob
spec:
  schedule: "0 2 * * *"  # 매일 오전 2시에 실행
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-container
            image: chickennight/batch-server:0.0.1
            env:
              - name: DATASOURCE_URL
                value: jdbc:postgresql://${DB_ENDPOINT}:${DB_PORT}/wordsketch?serverTimezone=UTC+9&characterEncoding=UTF-8
              - name: DATASOURCE_USERNAME
                value: postgres
              - name: DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: password
              - name: DB_ENDPOINT
                valueFrom:
                  configMapKeyRef:
                    name: db-config
                    key: endpoint
              - name: DB_PORT
                valueFrom:
                  configMapKeyRef:
                    name: db-config
                    key: port
            restartPolicy: OnFailure
