apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-cronjob
  namespace: web
spec:
  schedule: "20 6 * * *"  # 매일 오전 2시에 실행
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-container
            image: chickennight/batch-server:0.2.3
            env:
              - name: SPRING_DATASOURCE_URL
                valueFrom:
                  configMapKeyRef:
                    name: db-config
                    key: url
              - name: SPRING_DATASOURCE_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: username
              - name: SPRING_DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-secrets
                    key: password
              - name: AWS_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-secret
                    key: aws_access_key_id
              - name: AWS_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-secret
                    key: aws_secret_access_key
              - name: OPENAI_KEY
                valueFrom:
                  secretKeyRef:
                    name: openai-secret
                    key: api_key
          restartPolicy: OnFailure  # 여기로 옮겨짐
