apiVersion: apps/v1
kind: Deployment
metadata:
  name: pants-rank
  namespace: web
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pants-rank
  template:
    metadata:
      labels:
        app: pants-rank
    spec:
      containers:
        - name: pants-rank
          image: chickennight/pants-rank:0.0.0
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-config
                  key: url
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-config
                  key: url
