apiVersion: apps/v1
kind: Deployment
metadata:
  name: pants-oauth
  namespace: web
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: pants-oauth
  template:
    metadata:
      labels:
        app: pants-oauth
    spec:
      containers:
        - name: pants-oauth
          image: chickennight/pants-oauth:4.0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: GOOGLE_REDIRECT_URI
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: GITHUB_CLIENT_SECRET
            - name: GITHUB_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: GITHUB_REDIRECT_URI
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: KAKAO_CLIENT_ID
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: KAKAO_CLIENT_SECRET
            - name: KAKAO_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: KAKAO_REDIRECT_URI
            - name: JWT_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: JWT_SECRETKEY
